//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Access_Employee_Type
    {
        public int Employee_Type_ID { get; set; }
        public int Access_ID { get; set; }
        public bool Acess { get; set; }
    
        public virtual Access Access { get; set; }
        public virtual Employee_Type Employee_Type { get; set; }
    }
}
