//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Audit()
        {
            this.Audit_Detail = new HashSet<Audit_Detail>();
            this.Audit_Update_Detail = new HashSet<Audit_Update_Detail>();
        }
    
        public int Audit_ID { get; set; }
        public string Table { get; set; }
        public System.DateTime Date { get; set; }
        public int Employee_ID { get; set; }
        public string Employee_Name { get; set; }
        public int Audit_Type_ID { get; set; }
    
        public virtual Audit_Type Audit_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Audit_Detail> Audit_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Audit_Update_Detail> Audit_Update_Detail { get; set; }
    }
}
