//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_Quote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client_Quote()
        {
            this.Client_Quote_Detail = new HashSet<Client_Quote_Detail>();
        }
    
        public int Client_Quote_ID { get; set; }
        public System.DateTime Date { get; set; }
        public int Client_ID { get; set; }
        public int Contact_ID { get; set; }
        public System.DateTime Client_Quote_Expiry_Date { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Client_Contact_Person_Detail Client_Contact_Person_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client_Quote_Detail> Client_Quote_Detail { get; set; }
    }
}
