//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_Order_Detail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client_Order_Detail()
        {
            this.Client_Credit_Order = new HashSet<Client_Credit_Order>();
            this.Delivery_Note_Details = new HashSet<Delivery_Note_Details>();
        }
    
        public int Client_Order_Detail_ID { get; set; }
        public int Quantity { get; set; }
        public int Quantity_Delivered { get; set; }
        public decimal Part_Price { get; set; }
        public double Client_Discount_Rate { get; set; }
        public int Client_Order_ID { get; set; }
        public int Part_Type_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client_Credit_Order> Client_Credit_Order { get; set; }
        public virtual Client_Order Client_Order { get; set; }
        public virtual Part_Type Part_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Delivery_Note_Details> Delivery_Note_Details { get; set; }
    }
}
