//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client_Order()
        {
            this.Client_Order_Detail = new HashSet<Client_Order_Detail>();
            this.Contracted_Client_Orders = new HashSet<Contracted_Client_Orders>();
            this.Delivery_Note = new HashSet<Delivery_Note>();
        }
    
        public int Client_Order_ID { get; set; }
        public System.DateTime Date { get; set; }
        public string Reference_ID { get; set; }
        public int Contact_ID { get; set; }
        public int Client_ID { get; set; }
        public double Settlement_Discount_Rate { get; set; }
        public int Client_Order_Type_ID { get; set; }
        public int Client_Order_Status_ID { get; set; }
        public int Delivery_Method_ID { get; set; }
        public int Job_Card_ID { get; set; }
        public bool VAT_Inclu { get; set; }
        public string Comment { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Client_Order_Type Client_Order_Type { get; set; }
        public virtual Client_Order_Status Client_Order_Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client_Order_Detail> Client_Order_Detail { get; set; }
        public virtual Delivery_Method Delivery_Method { get; set; }
        public virtual Job_Card Job_Card { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contracted_Client_Orders> Contracted_Client_Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Delivery_Note> Delivery_Note { get; set; }
    }
}
