//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Client_Contact_Person_Detail = new HashSet<Client_Contact_Person_Detail>();
            this.Client_Discount_Rate = new HashSet<Client_Discount_Rate>();
            this.Client_Order = new HashSet<Client_Order>();
            this.Client_Quote = new HashSet<Client_Quote>();
        }
    
        public int Client_ID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Zip { get; set; }
        public decimal Overdue_Payment { get; set; }
        public string Vat_Number { get; set; }
        public string Account_Name { get; set; }
        public double Contract_Discount_Rate { get; set; }
        public bool Client_Status { get; set; }
        public int Province_ID { get; set; }
        public double Settlement_Discount_Rate { get; set; }
    
        public virtual Province Province { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client_Contact_Person_Detail> Client_Contact_Person_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client_Discount_Rate> Client_Discount_Rate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client_Order> Client_Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client_Quote> Client_Quote { get; set; }
    }
}
