//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_Credit_Order
    {
        public int Client_Credit_Order_ID { get; set; }
        public int Quantity_Returned { get; set; }
        public System.DateTime Date_Returned { get; set; }
        public int Client_Order_Detail_ID { get; set; }
        public string Return_Comment { get; set; }
    
        public virtual Client_Order_Detail Client_Order_Detail { get; set; }
    }
}
