//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Component
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Component()
        {
            this.Component_Supplier = new HashSet<Component_Supplier>();
            this.Supplier_Quote_Component = new HashSet<Supplier_Quote_Component>();
            this.Supplier_Order_Component = new HashSet<Supplier_Order_Component>();
        }
    
        public int Component_ID { get; set; }
        public int Quantity { get; set; }
        public decimal Unit_Price { get; set; }
        public string Description { get; set; }
        public string Dimension { get; set; }
        public string Name { get; set; }
        public int Min_Stock { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Component_Supplier> Component_Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supplier_Quote_Component> Supplier_Quote_Component { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supplier_Order_Component> Supplier_Order_Component { get; set; }
    }
}
