//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Component_Supplier
    {
        public bool is_preferred { get; set; }
        public decimal unit_price { get; set; }
        public int Component_ID { get; set; }
        public int Supplier_ID { get; set; }
    
        public virtual Component Component { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
