//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contracted_Client_Orders
    {
        public int Contract_Client_Order_ID { get; set; }
        public int Client_Order_ID { get; set; }
        public string Mine_Name { get; set; }
        public double Contract_Discount_Rate { get; set; }
    
        public virtual Client_Order Client_Order { get; set; }
    }
}
