//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Credit_Detail
    {
        public int Customer_Credit_ID { get; set; }
        public int Part_ID { get; set; }
        public int Client_Order_Detail_ID { get; set; }
        public string Status { get; set; }
    
        public virtual Customer_Credit Customer_Credit { get; set; }
        public virtual Part Part { get; set; }
    }
}
