//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery_Note_Details
    {
        public int Quantity_Delivered { get; set; }
        public int Client_Order_Detail_ID { get; set; }
        public int Delivery_Note_ID { get; set; }
    
        public virtual Client_Order_Detail Client_Order_Detail { get; set; }
        public virtual Delivery_Note Delivery_Note { get; set; }
    }
}
