//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Photo
    {
        public int photo_ID { get; set; }
        public int Employee_ID { get; set; }
        public string Name { get; set; }
        public string File_Type { get; set; }
        public string Name_on_Server { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
