//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice_Payment
    {
        public int Payment_ID { get; set; }
        public int Invoice_ID { get; set; }
        public System.DateTime Payment_Date { get; set; }
        public decimal Amount_Paid { get; set; }
    
        public virtual Invoice Invoice { get; set; }
    }
}
