//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job_Card
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job_Card()
        {
            this.Client_Order = new HashSet<Client_Order>();
            this.Job_Card_Detail = new HashSet<Job_Card_Detail>();
            this.Production_Task = new HashSet<Production_Task>();
        }
    
        public int Job_Card_ID { get; set; }
        public System.DateTime Job_Card_Date { get; set; }
        public int Job_Card_Status_ID { get; set; }
        public int Job_Card_Priority_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client_Order> Client_Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Job_Card_Detail> Job_Card_Detail { get; set; }
        public virtual Job_Card_Status Job_Card_Status { get; set; }
        public virtual Job_Card_Priority Job_Card_Priority { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Production_Task> Production_Task { get; set; }
    }
}
