//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Machine_Part
    {
        public int Stage_In_Manufacturing { get; set; }
        public int Machine_ID { get; set; }
        public int Part_Type_ID { get; set; }
    
        public virtual Machine Machine { get; set; }
        public virtual Part_Type Part_Type { get; set; }
    }
}
