//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Part_Blueprint
    {
        public int Blueprint_ID { get; set; }
        public string Name { get; set; }
        public string File_Type { get; set; }
        public string location { get; set; }
        public int Part_Type_ID { get; set; }
    
        public virtual Part_Type Part_Type { get; set; }
    }
}
