//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Part_Type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Part_Type()
        {
            this.Client_Discount_Rate = new HashSet<Client_Discount_Rate>();
            this.Client_Order_Detail = new HashSet<Client_Order_Detail>();
            this.Client_Quote_Detail = new HashSet<Client_Quote_Detail>();
            this.Job_Card_Detail = new HashSet<Job_Card_Detail>();
            this.Machine_Part = new HashSet<Machine_Part>();
            this.Manual_Labour_Type_Part = new HashSet<Manual_Labour_Type_Part>();
            this.Parts = new HashSet<Part>();
            this.Part_Blueprint = new HashSet<Part_Blueprint>();
            this.Part_Supplier = new HashSet<Part_Supplier>();
            this.Recipes = new HashSet<Recipe>();
            this.Supplier_Quote_Detail_Part = new HashSet<Supplier_Quote_Detail_Part>();
            this.Supplier_Order_Detail_Part = new HashSet<Supplier_Order_Detail_Part>();
        }
    
        public int Part_Type_ID { get; set; }
        public string Abbreviation { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Selling_Price { get; set; }
        public string Dimension { get; set; }
        public int Minimum_Level { get; set; }
        public int Maximum_Level { get; set; }
        public int Max_Discount_Rate { get; set; }
        public bool Manufactured { get; set; }
        public int Average_Completion_Time { get; set; }
        public int Number_Of_Stages { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client_Discount_Rate> Client_Discount_Rate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client_Order_Detail> Client_Order_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client_Quote_Detail> Client_Quote_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Job_Card_Detail> Job_Card_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Machine_Part> Machine_Part { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Manual_Labour_Type_Part> Manual_Labour_Type_Part { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Part> Parts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Part_Blueprint> Part_Blueprint { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Part_Supplier> Part_Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recipe> Recipes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supplier_Quote_Detail_Part> Supplier_Quote_Detail_Part { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supplier_Order_Detail_Part> Supplier_Order_Detail_Part { get; set; }
    }
}
