//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Production_Task
    {
        public int Production_Task_ID { get; set; }
        public string Production_Task_Type { get; set; }
        public int Resource_ID { get; set; }
        public int Part_Stage { get; set; }
        public int Part_ID { get; set; }
        public int Job_Card_ID { get; set; }
        public int Production_Schedule_ID { get; set; }
        public int Employee_ID { get; set; }
        public System.TimeSpan start_time { get; set; }
        public System.TimeSpan end_time { get; set; }
        public int duration { get; set; }
        public bool complete { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Job_Card Job_Card { get; set; }
        public virtual Part Part { get; set; }
        public virtual Production_Schedule Production_Schedule { get; set; }
    }
}
