//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProteusEntities : DbContext
    {
        public ProteusEntities()
            : base("name=ProteusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Access> Accesses { get; set; }
        public virtual DbSet<Access_Employee_Type> Access_Employee_Type { get; set; }
        public virtual DbSet<Audit> Audits { get; set; }
        public virtual DbSet<Audit_Detail> Audit_Detail { get; set; }
        public virtual DbSet<Audit_Type> Audit_Type { get; set; }
        public virtual DbSet<Audit_Update_Detail> Audit_Update_Detail { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Client_Contact_Person_Detail> Client_Contact_Person_Detail { get; set; }
        public virtual DbSet<Client_Credit_Order> Client_Credit_Order { get; set; }
        public virtual DbSet<Client_Discount_Rate> Client_Discount_Rate { get; set; }
        public virtual DbSet<Client_Order> Client_Order { get; set; }
        public virtual DbSet<Client_Order_Detail> Client_Order_Detail { get; set; }
        public virtual DbSet<Client_Order_Status> Client_Order_Status { get; set; }
        public virtual DbSet<Client_Order_Type> Client_Order_Type { get; set; }
        public virtual DbSet<Client_Quote> Client_Quote { get; set; }
        public virtual DbSet<Client_Quote_Detail> Client_Quote_Detail { get; set; }
        public virtual DbSet<Component> Components { get; set; }
        public virtual DbSet<Component_Supplier> Component_Supplier { get; set; }
        public virtual DbSet<Contracted_Client_Orders> Contracted_Client_Orders { get; set; }
        public virtual DbSet<Customer_Credit> Customer_Credit { get; set; }
        public virtual DbSet<Customer_Credit_Detail> Customer_Credit_Detail { get; set; }
        public virtual DbSet<Delivery_Method> Delivery_Method { get; set; }
        public virtual DbSet<Delivery_Note> Delivery_Note { get; set; }
        public virtual DbSet<Delivery_Note_Details> Delivery_Note_Details { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Employee_Photo> Employee_Photo { get; set; }
        public virtual DbSet<Employee_Type> Employee_Type { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<Invoice_Payment> Invoice_Payment { get; set; }
        public virtual DbSet<Invoice_Status> Invoice_Status { get; set; }
        public virtual DbSet<Job_Card> Job_Card { get; set; }
        public virtual DbSet<Job_Card_Detail> Job_Card_Detail { get; set; }
        public virtual DbSet<Job_Card_Priority> Job_Card_Priority { get; set; }
        public virtual DbSet<Job_Card_Status> Job_Card_Status { get; set; }
        public virtual DbSet<Machine> Machines { get; set; }
        public virtual DbSet<Machine_Part> Machine_Part { get; set; }
        public virtual DbSet<Machine_Status> Machine_Status { get; set; }
        public virtual DbSet<Manual_Labour_Type> Manual_Labour_Type { get; set; }
        public virtual DbSet<Manual_Labour_Type_Part> Manual_Labour_Type_Part { get; set; }
        public virtual DbSet<Part> Parts { get; set; }
        public virtual DbSet<Part_Blueprint> Part_Blueprint { get; set; }
        public virtual DbSet<Part_Status> Part_Status { get; set; }
        public virtual DbSet<Part_Supplier> Part_Supplier { get; set; }
        public virtual DbSet<Part_Type> Part_Type { get; set; }
        public virtual DbSet<Production_Schedule> Production_Schedule { get; set; }
        public virtual DbSet<Production_Task> Production_Task { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<Raw_Material> Raw_Material { get; set; }
        public virtual DbSet<Raw_Material_Supplier> Raw_Material_Supplier { get; set; }
        public virtual DbSet<Recipe> Recipes { get; set; }
        public virtual DbSet<Sub_Contractor> Sub_Contractor { get; set; }
        public virtual DbSet<Sub_Contractor_Contact_Detail> Sub_Contractor_Contact_Detail { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<Supplier_Order> Supplier_Order { get; set; }
        public virtual DbSet<Supplier_Order_Component> Supplier_Order_Component { get; set; }
        public virtual DbSet<Supplier_Order_Detail_Part> Supplier_Order_Detail_Part { get; set; }
        public virtual DbSet<Supplier_Order_Detail_Raw_Material> Supplier_Order_Detail_Raw_Material { get; set; }
        public virtual DbSet<Supplier_Order_Status> Supplier_Order_Status { get; set; }
        public virtual DbSet<Supplier_Quote> Supplier_Quote { get; set; }
        public virtual DbSet<Supplier_Quote_Component> Supplier_Quote_Component { get; set; }
        public virtual DbSet<Supplier_Quote_Detail_Part> Supplier_Quote_Detail_Part { get; set; }
        public virtual DbSet<Supplier_Quote_Detail_Raw_Material> Supplier_Quote_Detail_Raw_Material { get; set; }
        public virtual DbSet<Supplier_Return> Supplier_Return { get; set; }
        public virtual DbSet<Supplier_Return_Item> Supplier_Return_Item { get; set; }
        public virtual DbSet<Unique_Machine> Unique_Machine { get; set; }
        public virtual DbSet<Unique_Raw_Material> Unique_Raw_Material { get; set; }
        public virtual DbSet<VAT> VATs { get; set; }
    }
}
