//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Raw_Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Raw_Material()
        {
            this.Raw_Material_Supplier = new HashSet<Raw_Material_Supplier>();
            this.Supplier_Quote_Detail_Raw_Material = new HashSet<Supplier_Quote_Detail_Raw_Material>();
            this.Supplier_Order_Detail_Raw_Material = new HashSet<Supplier_Order_Detail_Raw_Material>();
            this.Unique_Raw_Material = new HashSet<Unique_Raw_Material>();
        }
    
        public string Name { get; set; }
        public string Description { get; set; }
        public int Minimum_Stock_Instances { get; set; }
        public int Raw_Material_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Raw_Material_Supplier> Raw_Material_Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supplier_Quote_Detail_Raw_Material> Supplier_Quote_Detail_Raw_Material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supplier_Order_Detail_Raw_Material> Supplier_Order_Detail_Raw_Material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Unique_Raw_Material> Unique_Raw_Material { get; set; }
    }
}
