//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sub_Contractor_Contact_Detail
    {
        public int Contact_ID { get; set; }
        public int Sub_Contractor_ID { get; set; }
        public string Number { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
    
        public virtual Sub_Contractor Sub_Contractor { get; set; }
    }
}
