//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sub_Contractor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sub_Contractor()
        {
            this.Sub_Contractor_Contact_Detail = new HashSet<Sub_Contractor_Contact_Detail>();
        }
    
        public int Sub_Contractor_ID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Zip { get; set; }
        public bool Status { get; set; }
        public int Manual_Labour_Type_ID { get; set; }
        public int Province_ID { get; set; }
    
        public virtual Manual_Labour_Type Manual_Labour_Type { get; set; }
        public virtual Province Province { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sub_Contractor_Contact_Detail> Sub_Contractor_Contact_Detail { get; set; }
    }
}
