//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier_Order_Component
    {
        public int Component_ID { get; set; }
        public int Quantity_Requested { get; set; }
        public int Quantity_Received { get; set; }
        public decimal Price { get; set; }
        public int Supplier_Order_ID { get; set; }
    
        public virtual Component Component { get; set; }
        public virtual Supplier_Order Supplier_Order { get; set; }
    }
}
