//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier_Return
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier_Return()
        {
            this.Supplier_Return_Item = new HashSet<Supplier_Return_Item>();
        }
    
        public int Supplier_Return_ID { get; set; }
        public int Supplier_Order_ID { get; set; }
        public System.DateTime Date_of_Return { get; set; }
        public string Invoice_Number { get; set; }
        public string Delivery_Note_Number { get; set; }
        public string Comment { get; set; }
    
        public virtual Supplier_Order Supplier_Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supplier_Return_Item> Supplier_Return_Item { get; set; }
    }
}
