//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier_Quote_Detail_Raw_Material
    {
        public int Supplier_Quote_ID { get; set; }
        public int Raw_Material_ID { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
        public string Dimension { get; set; }
    
        public virtual Raw_Material Raw_Material { get; set; }
        public virtual Supplier_Quote Supplier_Quote { get; set; }
    }
}
