//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier_Quote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier_Quote()
        {
            this.Supplier_Quote_Component = new HashSet<Supplier_Quote_Component>();
            this.Supplier_Quote_Detail_Part = new HashSet<Supplier_Quote_Detail_Part>();
            this.Supplier_Quote_Detail_Raw_Material = new HashSet<Supplier_Quote_Detail_Raw_Material>();
        }
    
        public int Supplier_Quote_ID { get; set; }
        public string Supplier_Quote_Serial { get; set; }
        public System.DateTime Supplier_Quote_Date { get; set; }
        public int Supplier_ID { get; set; }
        public System.DateTime Supplier_Quote_Expiry_Date { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supplier_Quote_Component> Supplier_Quote_Component { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supplier_Quote_Detail_Part> Supplier_Quote_Detail_Part { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supplier_Quote_Detail_Raw_Material> Supplier_Quote_Detail_Raw_Material { get; set; }
        public virtual Supplier_Order Supplier_Order { get; set; }
    }
}
