//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier_Return_Item
    {
        public int Return_Item_ID { get; set; }
        public int Supplier_Return_ID { get; set; }
        public string Type_of_Inventory { get; set; }
        public int Inventory_ID { get; set; }
        public int Units_Returned { get; set; }
        public string Item_Name { get; set; }
    
        public virtual Supplier_Return Supplier_Return { get; set; }
    }
}
