//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier_Order_Detail_Raw_Material
    {
        public int Quantity { get; set; }
        public decimal Price { get; set; }
        public int Quantity_Received { get; set; }
        public string Dimensions { get; set; }
        public int Raw_Material_ID { get; set; }
        public int Supplier_Order_ID { get; set; }
    
        public virtual Raw_Material Raw_Material { get; set; }
        public virtual Supplier_Order Supplier_Order { get; set; }
    }
}
