//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unique_Raw_Material
    {
        public int Unique_Raw_Material_ID { get; set; }
        public int Raw_Material_ID { get; set; }
        public string Dimension { get; set; }
        public string Quality { get; set; }
        public System.DateTime Date_Added { get; set; }
        public Nullable<System.DateTime> Date_Used { get; set; }
        public decimal Cost_Price { get; set; }
        public Nullable<int> Supplier_Order_ID { get; set; }
    
        public virtual Raw_Material Raw_Material { get; set; }
        public virtual Supplier_Order Supplier_Order { get; set; }
    }
}
