//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unique_Machine
    {
        public int Unique_Machine_ID { get; set; }
        public string Unique_Machine_Serial { get; set; }
        public int Machine_Status_ID { get; set; }
        public int Machine_ID { get; set; }
    
        public virtual Machine Machine { get; set; }
        public virtual Machine_Status Machine_Status { get; set; }
    }
}
